//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INV_NP_COMPROMETIDAS_N
    {
        public int id_np_comprometidas { get; set; }
        public string sticker { get; set; }
        public string id_alm_ent { get; set; }
        public decimal org_lvl_child { get; set; }
        public decimal id_estado { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public Nullable<decimal> qty_pend { get; set; }
        public string sku_id { get; set; }
        public Nullable<decimal> number_1 { get; set; }
        public Nullable<decimal> number_2 { get; set; }
        public string vchar_1 { get; set; }
        public string vchar_2 { get; set; }
    }
}
