//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INV_CO_DESPACHADAS_N
    {
        public int id_co_despachadas { get; set; }
        public string whse { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> co_desp { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<decimal> number_1 { get; set; }
        public Nullable<decimal> number_2 { get; set; }
        public string vchar_1 { get; set; }
        public string vchar_2 { get; set; }
    }
}
