//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INV_UBICACIONES_N
    {
        public int id_ubicacion { get; set; }
        public decimal id_item { get; set; }
        public string whse { get; set; }
        public string sku_id { get; set; }
        public string prd_lvl_child { get; set; }
        public string ubicacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public Nullable<decimal> on_hand_qty { get; set; }
        public string wms_locn_id { get; set; }
        public Nullable<decimal> number_1 { get; set; }
        public Nullable<decimal> number_2 { get; set; }
        public string vchar_1 { get; set; }
        public string vchar_2 { get; set; }
    }
}
